### ISSUE TITLE
Failed to resolve: com.mindorks.android:prdownloader:0.5.0

### ISSUE THREAD

**Issue by swamy3697** [amitshekhariitbhu/PRDownloader#205]
cannot resovle Prdownloader and im not able to use the class help me

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu:PRDownloader:1.0.1'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu:PRDownloader:1.0.1")
```

**Comment by swamy3697** [comment]
Thank you
