### ISSUE TITLE
404 Not found !

### ISSUE THREAD

**Issue by abir-cse** [amitshekhariitbhu/PRDownloader#214]
The library is not working on Android Studio. Showing 404 error on download links.
Problem with jitpack :(

**Comment by amitshekhariitbhu** [comment]
Checking and fixing it.

**Comment by amitshekhariitbhu** [comment]
@abir-cse 

Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
implementation 'com.github.amitshekhariitbhu:PRDownloader:1.0.1'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
implementation("com.github.amitshekhariitbhu:PRDownloader:1.0.1")
```

**Comment by abir-cse** [comment]
It's working.
Thank you.
